@startuml CONTEXT
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
'!include C4_Component.puml

title Diagrama de Contexto do Monitor Multiparamétrico

System_Boundary(Interface, "Interface"){
    Container(user_webApp, "Admin WebApp", "HTML/CSS/JS", "Disponibiliza comandos para iniciar e interromper aferições, exibe os dados dos sensores"){
        Component(network, "Configurações de Rede", "Lista de endereços para conexão, inserção de dados para login em redes Wifi, Lista de dispositivos conectados em modo")
        Component(files, "Gerenciamento de arquivos", "HTML/CSS/JS", "Envio, visualização e exclusão de arquivos que são requisitados para a interface do usuário")
    }
    Container(api, "api", "C", "Processa as requisições do usuário/admin. Disponibiliza endpoints para transferência dos dados dos sensores. Envia comandos para as APIs dos sensores. ")
    ContainerDb(spiffs, "SPIFFS", "ROM", "Armazena arquivos de definição da interface do usuário (HTML, CSS, JS)")
}

Lay_D(network, api)
Lay_R(api, spiffs)

BiRel(network, api, "Requisita alteração/consulta de configurações", "HTTP")
BiRel(files, api, "Requisita carregamento/exclusão de arquivos ", "HTTP")
BiRel_R(api, spiffs, "Carrega/exclui arquivos ", "HTTP")

' SHOW_LEGEND(?hideStereotype, ?details)
SHOW_LEGEND()

@enduml